### PR TITLE
Fix GetEmoteSets method missing OwnerID in emote response

### LINKED ISSUE #98: Get Emote Sets missing OwnerID value
The [Get Emote Sets](https://github.com/nicklaw5/helix/blob/main/chat.go#L128) function is missing the `OwnerID` value returned [from the API](https://dev.twitch.tv/docs/api/reference#get-emote-sets).

The simple solution is to add `OwnerID` to the `Emote` type, but that'd mean an empty value in the other calls using the type (i.e. Get Channel Emotes and Get Global Emotes).
The complex solution is to return a different type in the response of Get Emote Sets.

I'm happy to make the change with a PR but I'd like to hear your preferred solution first.

### PR DESCRIPTION
**Pull request by pajlada**
- `GetEmoteSets` now returns a `GetEmoteSetsResponse` instead of `GetChannelEmotesResponse`
- Ensure emotes are marshalled properly in `TestGetEmoteSets`

There's still a few ways you could chose to do the emote type - I went with a "parent" type EmoteWithOwner - let me know if you have another preference.

Unrelated to the PR but I noteiced while working on this - The naming of the `Set_ID` parameter seems out of place among all the other members. Would love to see that changed to `SetID` but I'll create an issue for it instead of rambling on in this PR.

Fixes #98

### CODE REVIEW

File: chat_test.go [hunk 1]
```diff
@@ -302,18 +302,36 @@ func TestGetEmoteSets(t *testing.T) {
...
 			&GetEmoteSetsParams{EmoteSetIDs: []string{"300678379"}},
+			[]EmoteWithOwner{
+				{
+					Emote: Emote{
+						ID:   "301147694",
+						Name: "sixone3SixDab",
+						Images: EmoteImage{
+							Url1x: "https://static-cdn.jtvnw.net/emoticons/v1/301147694/1.0",
+							Url2x: "https://static-cdn.jtvnw.net/emoticons/v1/301147694/2.0",
+							Url4x: "https://static-cdn.jtvnw.net/emoticons/v1//3.0",
```
Comment (zneix) [inline chat_test.go:327]: No idea why is there no emote ID here. Would have to adjust JSON in line 335 as well.

```suggestion
							Url4x: "https://static-cdn.jtvnw.net/emoticons/v1/301147694/3.0",
```

**Review by zneix — CHANGES_REQUESTED** [review]

**Comment by nicklaw5** [comment]
Looks good. Can you please resolve @zneix's suggested change? Then I'm happy to merge.

**Comment by nicklaw5** [comment]
I've created #101 to resolve the `Set_ID` struct field.

**Review by zneix — APPROVED** [review]

**Review by nicklaw5 — APPROVED** [review]
